config/routes.rb
Rails.application.routes.draw do


  get '/servers/rockwell' => 'servers#rockwell'
  get '/rockwell/servers' => 'rockwell#server'

  post '/bookings' => 'bookings#create'

  post '/bookings' => 'bookings#create'

  root 'landing#index'
  get 'landing/index'

  get "/city/miami" => "club#index"
  get "/city" => "city#city"

  get "/tables" => 'reservationss#table'

  get '/login' => 'users#new'

  post '/users' => 'users#create'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get 'clubs/:clubname' => "rockwell#index"
  get 'clubs/:clubname/servers' => "servers#rockwell"
  get 'clubs/:clubname/reservations' => "reservations#index", as: 'reservations'
  post '/available_tables_for_date' => "reservations#tables", as: 'reserved_tables_for'
  post 'clubs/:clubname/reservations' => 'reservations#checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :table
  belongs_to :server
  belongs_to :user
  validates :table_id, presence: true
  validates :server_id, presence: true
  validates :user_id, presence: true
end

app/models/club.rb
class Club < ApplicationRecord
  has_many :floors
  has_many :servers
  has_many :tables, through: :floors
end

app/models/floor.rb
class Floor < ApplicationRecord
  belongs_to :club
  has_many :tables
  validates :club_id, presence: true

  def available_tables(day)
  	self.tables.reject { |t| t.bookings.where(day: day).count > 0 }
  end
end

app/models/server.rb
class Server < ApplicationRecord
  belongs_to :club
  has_many :bookings
  validates :club_id, presence: true
  SERVER_UPCHARGE = 150
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :floor
  has_many :bookings
  validates :floor_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bookings
	validates :firstname, presence: true
	validates :lastname, presence: true
  	validates :email, presence: true
	validates :email, uniqueness: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :save
	# validates :password_digest, presence: true
	has_secure_password


end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def city
  end
end

app/controllers/club_controller.rb
class ClubController < ApplicationController
  
  def index # display list of clubs
  	@club =  Club.all #this will have a view template
  end

  def show #shows one instance of club
  	@club =  Club.select(params[:id]) #this will have a view template
  end

  def new # makes a new instance of a club
  	#admid privalages
  end

  def create #saves record of new club
  	#admid privalages and will not have a view template
  end

  def edit #displays the form for an existing club
  	#admid privalages
  end

  def update #saves the form for an existing club
  	
  end

  def destroy #self explanitory
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render '/users/new'
    end
  end

private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/rockwell_helper.rb
module RockwellHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VRope</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Arizonia" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
  </head>


  <body>



    <%= yield %>

  </body>
</html>

app/views/layouts/rockwell.html.erb
<!DOCTYPE HTML>

<html>
	<head>
		<title>Rockwell</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link rel="stylesheet" href="/assets/main.css" />
		<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
	</head>
	<body class="is-preload">


		<!-- Header -->
			<header id="header">
				<a class="logo" href="index.html">Rockwell</a>
				<nav>
					<a href="#menu">Menu</a>
				</nav>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">

					<li><a href="./">Home</a></li>
					<li><a href="/clubs/rockwell/reservations">Reservations</a></li>
					<li><a href="/clubs/rockwell/servers">Servers</a></li>
					<li><a href="#">Login</a></li>
				</ul>
			</nav>

		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					<h1>Rockwell</h1>
					<p>"It ain't hard to tell, I rock well."<a href="#"></a></p>
				</div>
				<video autoplay loop muted playsinline>
					<source src="/assets/banner.mp4" type="video/mp4">
				</video>
				
			</section>

		<!-- Highlights -->
			<section class="wrapper">
				<div class="inner">
					<header class="special">
						<h2>Miami's Return to the Super Lounge</h2>
						<p>For those looking for the ultimate club experience, without having to deal with their crowd and long lines, Rockwell is the ultimate in Miami lounge nightlife!</p>
					</header>
					<div class="highlights">
						<section>
							<div class="content" id="servers">
								<header>
									 <%= link_to servers_rockwell_path do %> <i class="icon fa fa-fire"></i>
									 <% end %>
									<h3> <br></br>Servers</h3>
								</header>
								<p >Rockwell has some of the most beautiful servers and bottle girls in all of Miami. Click here to check out their staff and links to their server's instagram accounts. Afterwards, when making your table reservations, you can select which server you would like for your table.</p>
							</div>
						</section>
						<section>
							<div class="content" id="reservation">

                                <header>
                                <%= link_to reservations_path("Rockwell") do %>
                                    <i class="icon fa fa-table label"></i>
                                <% end %>
                                    <h3><br></br>Table Reservations</h3>
                                </header>
                                <p>Are you tired of having a table at the back of the club where you can't see the action? Are you tired of promoters putting you in a lame section next to a crowded bathroom line? Here at the Velvet Rope, not only can you select your server, but you can select the exact table you wish to reserve! Click here to start your reservation.</p>
                            </div>

						</section>
						<section>
							<div class="content" id="atmosphere">
								<header>
									<a href="" class="icon fa-paper-plane-o "><span class="label">Icon</span></a>
									<h3>Atmosphere</h3>
								</header>
								<p class="custom-text">The "atmosphere" package is a built in element of the Velvet Rope that keeps the balance and ratio of our clients in line with the venues requirements. Depending on the number of people in your group, you may be required to purchase this service. However, there have been only rave reviews from having the beauty and personalites of this package added to your purchase!.</p>
							</div>
						</section>
						<!-- <section> -->


					</div>
				</div>
<!-- 			</section> -->

		<!-- CTA -->
			<section id="cta" class="wrapper">
				<div class="inner">
					<h2>Why Rockwell You Might Ask?</h2>
					<p class="custom-text">
				Rockwell brings the perfect storm of LA cool, New York Music, and Miami energy to the space with this venture. Located on Washington Avenue, the concept pays hoage to Miami's rich history in nightlife, a rebirth of the space that formerly held the exclusive South Beach hotspons including Les Bains and Chaos..</p>
				</div>
			</section>

		<!-- Testimonials -->
			<section class="wrapper">
				<div class="inner">
					<header class="special">
						<h2>Local Reviews</h2>
						<p>Below are but some of the experiences our diverse community share.</p>
					</header>
					<div class="testimonials">
						<section>
							<div class="content">
								<blockquote>
									<p>This place has it all, for those of us who like to party with the best.</p>
								</blockquote>
								<div class="author">
									<div class="image">
										<img src="/assets/pic01.jpg" alt="" />
									</div>
									<p class="credit">- <strong>Jane Doe</strong> <span>Nightlife Connoisseur</span></p>
								</div>
							</div>
						</section>
						<section>
							<div class="content">
								<blockquote>
									<p>Whatever happens in Rockwell, stays in Rockwell...</p>
								</blockquote>
								<div class="author">
									<div class="image">
										<img src="/assets/pic03.jpg" alt="" />
									</div>
									<p class="credit">- <strong>John Doe</strong> <span>Entrepeneur</span></p>
								</div>
							</div>
						</section>
						<section>
							<div class="content">
								<blockquote>
									<p>The people here come to have a good time. The staff is warm and inviting. You'll love it.</p>
								</blockquote>
								<div class="author">
									<div class="image">
										<img src="/assets/pic02.jpg" alt="" />
									</div>
									<p class="credit">- <strong>Janet Smith</strong> <span>Instagram Model</span></p>
								</div>
							</div>
						</section>
					</div>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<div class="content">

						<section >
							<h4></h4>
							<div class="networks">
							<ul class="plain">
								<li><a href="https://twitter.com/rockwellmiami"><i class="icon fa-twitter">&nbsp;</i>Twitter</a></li>
								<li><a href="https://www.facebook.com/RockwellMiami"><i class="icon fa-facebook">&nbsp;</i>Facebook</a></li>
								<li><a href="https://www.instagram.com/rockwellmiami/"><i class="icon fa-instagram">&nbsp;</i>Instagram</a></li>
							</ul>
							</div>
						</section>
					</div>
					<div class="copyright">
						&copy; <a href="#">VelvetRope</a>.
					</div>
				</div>
			</footer>

		<!-- Scripts -->
			<script
				  src="https://code.jquery.com/jquery-3.3.1.min.js"
				  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
				  crossorigin="anonymous"></script>
			<script src="/assets/browser.min.js"></script>
			<script src="/assets/breakpoints.min.js"></script>
			<script src="/assets/util.js"></script>
			<script src="/assets/main.js"></script>


	</body>
</html>